### ISSUE TITLE
Supported VM types are outdated, many other vm types compatible now

### ISSUE THREAD

**Issue by kris1254** [NetAppDocs/cloud-volumes-ontap-97-relnotes#9]
Page: [Supported configurations in Azure](https://docs.netapp.com/us-en/cloud-volumes-ontap-97-relnotes/reference-configs-azure.html)

**Comment by netapp-bcammett** [comment]
@kris1254,

Thanks for reaching out. 

This page is specifically for Cloud Volumes ONTAP 9.7. Are you saying that other VM types are available with 9.7? Or are you referring to VM types supported with later versions of Cloud Volumes ONTAP?

Thanks,
Ben

**Comment by kris1254** [comment]
My bad, you’re right.

**Comment by netapp-bcammett** [comment]
No problem!
